### PR TITLE
[3.1.x] Added option to set a gate for the widget and added fallback locales

### PR DESCRIPTION
**Pull request by jordinbrouwer**
This pull request introduces several changes to the project:

- Implemented fallback locales, defaulting to the specified Laravel application locale and fallback locale.
- Added a gate for the widget.
- Removed redundant files, comments and elements.
- Updated project to better align with Filament 3.x standards.

I appreciate your dedication to enhancing this project and look forward to your feedback on these modifications. Thank you once again for your support and commitment to open source!

### CODE REVIEW

**Comment by jordinbrouwer** [comment]
Please note that the translation `saved_translation` is missing for `ar` and `es`. I could provide these using Google Translate if you would want.

**Comment by sten** [comment]
@jordinbrouwer Thanks a lot for all the tweaks! Looks very good.

I am bit hesitant to just renaming the config variables, semantically your proposal is a bit cleaner, but it will require all devs to upgrade the already published configuration manually and this is a nuisance. Either we should try to keep it compatible, or write an upgrade guide. What do you think?

You can use automated translations for the `saved_translation` key. Thanks!

**Comment by jordinbrouwer** [comment]
@sten I will write an update guide later today and include the missing translations.

**Comment by jordinbrouwer** [comment]
@sten I have added the missing translations and written an upgrade guide for `3.0` to `3.1`.

**Comment by sten** [comment]
@jordinbrouwer Thank you for the documentation. I made the configuration file changes backward compatible so upgrading is smoother. I will make a release now.

**Pull request merged**
